version: '3.9'
services:
  database:
    restart: always
    image: joshuaziegler/postgres_db:1.0.0
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

    ports:
      - "5432:5432"
    networks:
      appnet:
        ipv4_address: 172.24.2.1
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  data_grabber: 
    restart: always
    image: joshuaziegler/mvg_tracker:0.1.0
    volumes:
      - .:/mnt/external:rw
    command: python3 /root/workdir/data_gathering.py
    networks:
      appnet:
        ipv4_address: 172.24.2.2
networks:
  appnet:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.24.2.0/16"