version: '3.9'
services:
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker

    ports:
      - "5432:5432"
    networks:
      appnet:
        ipv4_address: 172.24.2.1
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
  data_grabber: 
    restart: always
    image: joshuaziegler/mvg_tracker:0.2.0
    volumes:
      # - C:/Users/joshu/OneDrive/Desktop/logging:/mnt/external
      - ~/Desktop/logging:/mnt/external/logs
      - ~/AppData/Roaming/MVG_Tracker/daily:/mnt/external/daily
    command: python3 /usr/local/lib/python3.8/dist-packages/mvg_tracker/__main__.py -l /mnt/external/logs -b /mnt/external/daily
    networks:
      appnet:
        ipv4_address: 172.24.2.2
networks:
  appnet:
      driver: bridge
      ipam:
          driver: default
          config:
              - subnet: "172.24.2.0/16"